name: Docker Image CI

on:
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]
  discussion_comment:
    types:
      [created,edited,deleted]
  pull_request_review_comment:
    types:
      [created,edited,deleted]
  discussion:
    types:
      [created,edited,deleted]
  issue_comment:
    types:
      [created,edited,deleted]
  pull_request_review:
    types:
      [submitted,edited,dismissed]
  workflow_dispatch:
  
  
env:
  IMAGE_NAME: authservice
  IMAGE_TAG: ${{ github.run_id }}

jobs:

  build-image:
    name: Build Container Image
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME:$IMAGE_TAG
